[General]
ApplicationVersion = '''0.5.6'''
FreeSpaceSearch = '''000000'''
FreeSpaceBuffer = '''040'''
NextExportID = '''0'''
ShowRawIVByteForTrainer = False

#################################
#################################
#################################
#################################
#################################
#################################
#################################
#################################
