name: Create PR from Template Changes
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch Changes from RHH Repo
        run: |
          git remote add template https://github.com/rh-hideout/pokeemerald-expansion.git
          git fetch template
          git checkout -b template-branch template/master
          git push origin template-branch:template-branch
  
      - name: Create PR of Changes
        run: |
          hub pull-request \
            -b fakuzatsu:master \
            -h fakuzatsu:template-branch \
            -m "Merge changes from the RHH repository"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}